/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,ts,jsx,tsx}', './src/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    // Layout shells
    'min-h-screen',
    'bg-slate-100',
    'bg-slate-200',
    'bg-zinc-100',
    'bg-gradient-to-br',
    'from-indigo-100',
    'via-slate-100',
    'to-white',
    'flex',
    'items-start',
    'justify-center',
    'shadow-xl',
    'shadow-lg',
    'shadow-2xl',
    'shadow-inner',
    'overflow-auto',
    'text-center',
    'justify-between',
    'rounded-lg',
    'w-[794px]',
    'w-[816px]',
    'min-h-[1123px]',
    'bg-white',
    'text-zinc-900',
    'text-slate-900',
    'text-slate-800',
    'p-10',
    'p-8',
    'px-12',
    'py-14',
    'px-10',
    'py-12',
    'px-10',
    'py-10',
    'pb-12',
    'pb-10',
    'p-6',
    'p-8',
    // Header
    'border-l-4',
    'border-zinc-900',
    'pl-4',
    'text-4xl',
    'text-5xl',
    'font-extrabold',
    'font-serif',
    'font-semibold',
    'font-bold',
    'tracking-tight',
    'text-zinc-600',
    'text-base',
    'text-lg',
    'text-xl',
    'uppercase',
    'tracking-[0.4em]',
    'text-slate-500',
    'text-slate-300',
    'pb-6',
    'border-b',
    'border-slate-300',
    'border-slate-200',
    'border-slate-100',
    'pb-2',
    'rounded-b-[3rem]',
    'rounded-2xl',
    'rounded-3xl',
    // Body grids
    'mt-4',
    'mt-8',
    'grid',
    'grid-cols-3',
    'grid-cols-2',
    'gap-6',
    'gap-3',
    'gap-2',
    'gap-1',
    'space-y-8',
    'space-y-6',
    'space-y-4',
    'space-y-3',
    'space-y-2',
    'space-y-1',
    'space-y-10',
    'col-span-1',
    'col-span-2',
    // Contact section
    'text-xs',
    'font-semibold',
    'tracking-wide',
    'mt-2',
    'text-sm',
    'space-y-1',
    'flex-wrap',
    'justify-center',
    'gap-x-8',
    'gap-y-2',
    'text-slate-700',
    'text-slate-100',
    // Skills
    'flex',
    'flex-wrap',
    'gap-2',
    'gap-3',
    'text-xs',
    'bg-zinc-100',
    'px-2',
    'py-1',
    'px-4',
    'py-3',
    'rounded',
    'rounded-full',
    'rounded-2xl',
    'border',
    'border-slate-300',
    'px-3',
    'py-1',
    'bg-indigo-50',
    'bg-indigo-100',
    'text-indigo-700',
    // Summary / text blocks
    'mt-1',
    'mt-3',
    'text-sm',
    'text-base',
    'leading-relaxed',
    'leading-tight',
    'text-slate-700',
    'text-slate-900',
    'text-white',
    'flex-col',
    'sm:flex-row',
    'sm:items-baseline',
    'sm:justify-between',
    'gap-1',
    'md:flex-row',
    'md:items-center',
    'md:justify-between',
    // Experience
    'space-y-4',
    'space-y-2',
    'space-y-3',
    'space-y-6',
    'text-sm',
    'font-medium',
    'text-zinc-700',
    'text-zinc-600',
    'text-zinc-500',
    'text-zinc-400',
    'text-slate-600',
    'text-slate-500',
    'text-indigo-600',
    'text-indigo-700',
    'list-disc',
    'ml-5',
    'ml-6',
    // Education
    'text-slate-700',
    'text-slate-600',
    // Responsive gaps
    'gap-2',
    'gap-3',
    // Projects
    'underline',
    'transition-colors',
    'hover:text-indigo-500'
  ],
  theme: {
    extend: {}
  },
  plugins: []
};
