# --- AUTH ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: petchluvsyou/auth-service:latest
          env:
            - name: NODE_ENV
              value: "production"
            - name: SQL_URL
              value: "postgresql://user:pass@postgres:5432/main"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: RABBITMQ_URL
              value: "amqp://user:pass@rabbitmq:5672"
            - name: COOKIE_DOMAIN
              value: ""
            - name: FRONTEND_URL
              value: "http://192.168.0.210"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template
  template:
    metadata:
      labels:
        app: template
    spec:
      containers:
        - name: template
          image: petchluvsyou/template-service:latest
          env:
            - name: NODE_ENV
              value: "development"
            - name: MONGO_URL
              value: "mongodb://mongo:27017/careercraft_templates"
            - name: AUTH_GRPC_URL
              value: "auth:50051"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
        - name: resume
          image: petchluvsyou/resume-service:latest
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGO_URL
              value: "mongodb://mongo:27017/careercraft_resumes"
            - name: AUTH_GRPC_URL
              value: "auth:50051"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noti
  template:
    metadata:
      labels:
        app: noti
    spec:
      containers:
        - name: noti
          image: petchluvsyou/noti-service:latest
          env:
            - name: RABBITMQ_URL
              value: "amqp://user:pass@rabbitmq:5672"
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: sendgrid-key

